<a href="https://colab.research.google.com/github/young-hyun-park/capston_design/blob/main/inceptionv3_multilabelclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
from glob import glob
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import datasets, transforms
from torchvision.io import decode_image, read_file
from torchsummary import summary
from PIL import Image
import os
import re
import nibabel as nib

## Data loading

In [2]:
zip_path = sorted(glob('/content/drive/Shareddrives/캡스톤 디자인1/dataset/original_512/*'))

In [3]:
import zipfile
for path in zip_path:
  zip_file = zipfile.ZipFile(path)
  zip_file.extractall('/content/datasets/'+path.split('/')[-1].split('.')[0])
  zip_file.close()

In [4]:
my_glob = glob('/content/datasets/images*/*.png')
print('Number of Observations: ', len(my_glob))

Number of Observations:  76666


In [5]:
df = pd.read_csv('/content/drive/Shareddrives/캡스톤 디자인1/NIH_Dataframe.csv')

In [6]:
full_img_paths = {os.path.basename(x): x for x in my_glob}
df['full_path'] = df['img_ind'].map(full_img_paths.get)

In [7]:
df

Cardiomegaly  Hernia  Infiltration  Nodule  Emphysema  Effusion  \
0               1.0     0.0           0.0     0.0        0.0       0.0   
1               1.0     0.0           0.0     0.0        1.0       0.0   
2               1.0     0.0           0.0     0.0        0.0       1.0   
3               0.0     1.0           0.0     0.0        0.0       0.0   
4               0.0     1.0           0.0     0.0        0.0       0.0   
...             ...     ...           ...     ...        ...       ...   
51754           0.0     0.0           0.0     0.0        0.0       0.0   
51755           0.0     0.0           1.0     0.0        0.0       0.0   
51756           0.0     0.0           0.0     1.0        0.0       0.0   
51757           0.0     0.0           0.0     0.0        0.0       0.0   
51758           0.0     0.0           0.0     0.0        0.0       0.0   

       Atelectasis  Pleural_Thickening  Pneumothorax  Mass  Fibrosis  \
0              0.0                 0.0           0.0   0.0       0.0   
1              0.0                 0.0           0.0   0.0       0.0   
2              0.0                 0.0           0.0   0.0       0.0   
3              0.0                 0.0           0.0   0.0       0.0   
4              0.0                 0.0           0.0   0.0       0.0   
...            ...                 ...           ...   ...       ...   
51754          0.0                 1.0           0.0   0.0       0.0   
51755          0.0                 0.0           0.0   0.0       0.0   
51756          0.0                 0.0           0.0   1.0       0.0   
51757          0.0                 1.0           0.0   0.0       0.0   
51758          0.0                 0.0           0.0   1.0       0.0   

       Consolidation  Edema  Pneumonia           img_ind  \
0                0.0    0.0        0.0  00000001_000.png   
1                0.0    0.0        0.0  00000001_001.png   
2                0.0    0.0        0.0  00000001_002.png   
3                0.0    0.0        0.0  00000003_000.png   
4                0.0    0.0        0.0  00000003_001.png   
...              ...    ...        ...               ...   
51754            1.0    0.0        0.0  00030786_007.png   
51755            0.0    0.0        0.0  00030789_000.png   
51756            0.0    0.0        0.0  00030793_000.png   
51757            0.0    0.0        0.0  00030795_000.png   
51758            0.0    0.0        1.0  00030801_001.png   

                                          full_path  
0      /content/datasets/images_01/00000001_000.png  
1      /content/datasets/images_01/00000001_001.png  
2      /content/datasets/images_01/00000001_002.png  
3      /content/datasets/images_01/00000003_000.png  
4      /content/datasets/images_01/00000003_001.png  
...                                             ...  
51754  /content/datasets/images_12/00030786_007.png  
51755  /content/datasets/images_12/00030789_000.png  
51756  /content/datasets/images_12/00030793_000.png  
51757  /content/datasets/images_12/00030795_000.png  
51758  /content/datasets/images_12/00030801_001.png  

[51759 rows x 16 columns]

In [8]:
df_for_col = pd.read_csv('/content/drive/Shareddrives/캡스톤 디자인1/NIH_Dataframe.csv')
target_cols = df_for_col.drop(['img_ind'], axis=1).columns.to_list()
n_classes = len(target_cols)

In [9]:
n_classes

14

In [10]:
from sklearn.model_selection import train_test_split
paths = df['full_path'].values
columns = df.columns[:-2]
labels = df[columns].values
(train_path, val_path ,train_labels , val_labels) = train_test_split(paths,labels,test_size = 0.2,random_state = 42)

In [11]:
#pip install -U albumentations

In [12]:
!pip install --upgrade albumentations

     |████████████████████████████████| 102 kB 6.7 MB/s 
     |████████████████████████████████| 47.8 MB 129.2 MB/s 
  Attempting uninstall: albumentations
    Found existing installation: albumentations 0.1.12
    Uninstalling albumentations-0.1.12:
      Successfully uninstalled albumentations-0.1.12


In [13]:
#!pip uninstall opencv-python-headless

In [14]:
#!pip install opencv-python-headless==4.1.2.30

In [15]:
!pip install --upgrade opencv-python

     |████████████████████████████████| 60.5 MB 88.1 MB/s 
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30


## Data Loading

In [16]:
class Train_Dataset(Dataset):
    def __init__(self, data_path,labels, transform = None):
        self.data_path = data_path
        self.transform = transform
        self.labels = labels
    def __len__(self):
        return len(self.data_path)
    def __getitem__(self,idx):
        path = self.data_path[idx]
        img = np.array(Image.open(path))
        img = img/255
        img= np.stack((img,)*3, axis=-1)
        label = self.labels[idx]
        if self.transform is not None:
            transformed = self.transform(image=img)
            image = transformed['image']
        return image, label

In [17]:
class Val_Dataset(Dataset):
    def __init__(self, data_path,labels, transform = None):
        self.data_path = data_path
        self.transform = transform
        self.labels = labels
    def __len__(self):
        return len(self.data_path)
    def __getitem__(self,idx):
        path = self.data_path[idx]
        img = np.array(Image.open(path))
        img = img/255
        img= np.stack((img,)*3, axis=-1)
        label = self.labels[idx]
        if self.transform is not None:
            transformed = self.transform(image=img)
            image = transformed['image']
        return image, label

In [18]:
import albumentations as A                                                                           
from albumentations.pytorch import ToTensorV2

In [19]:
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

data_transforms = {
    'train': A.Compose(
    [
     ToTensorV2()
     ]
    ),
    'val': A.Compose([
                      ToTensorV2()   
    ]
                           )
}
'''
A.RandomCrop(224, 224),
     A.OneOf([
              A.HorizontalFlip(p=1),
              A.RandomRotate90(p=1),
              A.VerticalFlip(p=1)            
    ], p=1), 
'''

'\nA.RandomCrop(224, 224),\n     A.OneOf([\n              A.HorizontalFlip(p=1),\n              A.RandomRotate90(p=1),\n              A.VerticalFlip(p=1)            \n    ], p=1), \n'

## Model

In [20]:
pip install timm

     |████████████████████████████████| 431 kB 5.1 MB/s 


In [21]:
import timm

In [22]:
#timm.list_models(pretrained= True)

In [23]:
model = timm.create_model('tf_inception_v3', pretrained = True,num_classes = 14)

Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_inception_v3-e0069de4.pth" to /root/.cache/torch/hub/checkpoints/tf_inception_v3-e0069de4.pth


In [24]:
train_data = Train_Dataset(train_path,train_labels,transform = data_transforms['train'])
val_data = Val_Dataset(val_path,val_labels,transform =  data_transforms['val'])

In [38]:
# Top level data directory. Here we assume the format of the directory conforms
#   to the ImageFolder structure

# Models to choose from [resnet, alexnet, vgg, squeezenet, densenet, inception]

# Number of classes in the dataset
num_classes = 14
patience = 7
# Batch size for training (change depending on how much memory you have)
batch_size = 16

# Number of epochs to train for
num_epochs = 5

In [39]:
train_data = Train_Dataset(train_path,train_labels,transform = data_transforms['train'])
val_data = Val_Dataset(val_path,val_labels,transform =  data_transforms['val'])

In [40]:
image_datasets = {'train' : train_data , 'val' : val_data}
# Create training and validation dataloaders
dataloaders_dict = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=batch_size, shuffle=True) for x in ['train', 'val']}
# Detect if we have a GPU available
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [41]:
from __future__ import print_function
from __future__ import division
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score , roc_curve , accuracy_score,classification_report,multilabel_confusion_matrix,auc
import tqdm

In [42]:
from torch.types import Device
import torch.optim as optim
from torch.optim import lr_scheduler

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_ft = torch.load('/content/drive/Shareddrives/캡스톤 디자인1/codes/inceptionv3_multilabelclassification_1_10epoch.pt').to(device)
criterion = nn.BCEWithLogitsLoss()

# specify optimizer
optimizer_ft = optim.Adam(model_ft.parameters(), lr=0.0001)
sgdr_partial = lr_scheduler.CosineAnnealingLR(optimizer_ft, T_max=5, eta_min=0.005 )

In [43]:
class EarlyStopping:
    """Early stops the training if validation loss doesn't improve after a given patience."""
    def __init__(self, patience=7, verbose=False, delta=0, path='/content/drive/Shareddrives/캡스톤 디자인1/codes/resnet34_num14_dropout_augmented_multilabelclassfication_checkpoint.pt', trace_func=print):
        """
        Args:
            patience (int): How long to wait after last time validation loss improved.
                            Default: 7
            verbose (bool): If True, prints a message for each validation loss improvement. 
                            Default: False
            delta (float): Minimum change in the monitored quantity to qualify as an improvement.
                            Default: 0
            path (str): Path for the checkpoint to be saved to.
                            Default: 'checkpoint.pt'
            trace_func (function): trace print function.
                            Default: print            
        """
        self.patience = patience
        self.verbose = verbose
        self.counter = 0
        self.best_score = None
        self.early_stop = False
        self.val_loss_min = np.Inf
        self.delta = delta
        self.path = path
        self.trace_func = trace_func
    def __call__(self, val_loss, model):

        score = -val_loss

        if self.best_score is None:
            self.best_score = score
            #self.save_checkpoint(val_loss, model)
        elif score < self.best_score + self.delta:
            self.counter += 1
            self.trace_func(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            #self.save_checkpoint(val_loss, model)
            self.counter = 0

In [44]:
def train_model(model, dataloaders, criterion, optimizer, scheduler , num_epochs=25):
    since = time.time()
    train_acc_history = []
    train_loss_hist = [] 
    train_classification_report =[]
    train_confusion_matrix = []
    val_loss_hist = []
    val_acc_history = [] 
    val_classification_report =[]
    val_confusion_matrix = []
    epoch_train_label = []
    epoch_train_output = []
    epoch_val_label = []
    epoch_val_output = []

    best_model_wts = copy.deepcopy(model.state_dict())
    best_val_loss = 1000000000
    best_train_loss = 100000000
    early_stopping = EarlyStopping(patience = patience, verbose = True)
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch+1, num_epochs))
        print('-' * 10)
        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            start = time.time()
            print('phase : %r' %phase)
            if phase == 'train':
                model.train() # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_acc = 0
            running_precision =0
            running_recall = 0
            running_f1_score =0 
            running_auc = 0
            # Iterate over data.
            full_label = []
            full_output = []
            full_prediction = []
            for inputs, labels in tqdm.notebook.tqdm(dataloaders[phase]):
                inputs = inputs.to(device = device, dtype = torch.float32)
                labels = labels.to(device = device)
                # zero the parameter gradients
                optimizer.zero_grad()
                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    # Get model outputs and calculate loss
                    # Special case for inception because in training it has an auxiliary output. In train
                    #   mode we calculate the loss by summing the final output and the auxiliary output
                    #   but in testing we only consider the final output.
                    outputs = model(inputs)
                    loss = criterion(outputs,labels.float())
                    pred = nn.Sigmoid()(outputs)
                    full_prediction += pred.detach().cpu().numpy().tolist()
                    pred[pred <0.5] = 0
                    pred[pred >=0.5] = 1
                    if phase == 'train':
                    # backward + optimize only if in training phase
                        loss.backward()
                        optimizer.step()
                        scheduler.step()
                # statistics
                running_loss += loss.item() * inputs.size(0)
                full_label+= labels.detach().cpu().numpy().tolist()
                full_output+= pred.detach().cpu().numpy().tolist()
            epoch_loss = running_loss / len(dataloaders[phase].dataset)
            epoch_acc = accuracy_score(full_label,full_output)
            epoch_classification_report = classification_report(full_label,full_output,target_names = target_cols)
            epoch_multilabel_confusion_matrix = multilabel_confusion_matrix(full_label,full_output)
             
            if phase == 'train':
              train_acc_history.append(epoch_acc)
              train_loss_hist.append(epoch_loss)
              epoch_train_label.append(full_label)
              epoch_train_output.append(full_prediction)
              train_classification_report.append(epoch_classification_report)
              train_confusion_matrix.append(epoch_multilabel_confusion_matrix)
            print('\n{} Loss: {:.4f} Acc: {:.4f}, Time : {:.4f}'.format(phase, epoch_loss ,epoch_acc,time.time()-start))
            #,   , , epoch_precision,epoch_recall, epoch_auc, epoch_f1_score 
            print('\n--------------------------------')
            print('|{}Epoch {}phase multilabel_confusion_matrix report|'.format(epoch+1,phase))
            print('--------------------------------')
            print('\n{}'.format(epoch_multilabel_confusion_matrix))
            print('\n--------------------------------')
            print('\n{}Epoch {}phase classification report'.format(epoch+1,phase))
            print('--------------------------------')
            print(epoch_classification_report)

            # deep copy the model
            if phase == 'val' and train_loss_hist[-1] < best_train_loss:
                best_val_loss = epoch_loss
                best_train_loss = train_loss_hist[-1]
                best_model_wts = copy.deepcopy(model.state_dict())
            if phase == 'val':
                val_acc_history.append(epoch_acc)
                val_loss_hist.append(epoch_loss)
                epoch_val_label.append(full_label)
                epoch_val_output.append(full_prediction)
                val_classification_report.append(epoch_classification_report)
                val_confusion_matrix.append(multilabel_confusion_matrix)

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(time_elapsed // 60, time_elapsed % 60))
    print('Best train loss : {:.4f}  Best val loss: {:4f}'.format(best_train_loss ,best_val_loss))

    # load best model weights
    model.load_state_dict(best_model_wts)
    train_dict = {'Loss' : train_loss_hist , 'Accuarcy' : train_acc_history,'Classification_report' : train_classification_report,'Confusion_matrix' :train_confusion_matrix, 'train_label' : epoch_train_label , 'train_output' : epoch_train_output}
    #
    val_dict = {'Loss' :val_loss_hist , 'Accuarcy' : val_acc_history,'Classification_report' : val_classification_report,'val_label' : epoch_val_label , 'Confusion_matrix' :val_confusion_matrix,'val_output' : epoch_val_output}
    #, , 
    return model, train_dict ,val_dict

In [45]:
criterion = nn.BCEWithLogitsLoss()
import pickle
# Train and evaluate
for i in range(5):
  start = i*10+11
  end = (i+1)*10+10
  print('\n--------------------------------')
  print('|        Epoch {} ~ {}      |'.format(start, end))
  print('\n--------------------------------')
  model_ft, train_dict, val_dict  = train_model(model_ft, dataloaders_dict, criterion, optimizer_ft,sgdr_partial, num_epochs=10)
  torch.save(model_ft, '/content/drive/Shareddrives/캡스톤 디자인1/codes/inceptionv3_multilabelclassification_{}_{}epoch.pt'.format(start, end))
  with open('/content/drive/Shareddrives/캡스톤 디자인1/model_history/inceptionv3_multilabelclassification_{}_{}epoch_train_dict.pkl'.format(start, end),'wb') as fw:
    pickle.dump(train_dict, fw)
  with open('/content/drive/Shareddrives/캡스톤 디자인1/model_history/inceptionv3_multilabelclassification_{}_{}epoch_val_dict.pkl'.format(start, end),'wb') as ff:
    pickle.dump(val_dict, ff)
    
'''

confusion maxrix
[[true negative , false positive
false negative , true positive]]

[[tn , fp
fn , tp]]

'''


--------------------------------
|        Epoch 11 ~ 20      |

--------------------------------
Epoch 1/10
----------
phase : 'train'


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2489 Acc: 0.1819, Time : 564.8993

--------------------------------
|1Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38834   344]
  [ 1516   713]]

 [[41227     0]
  [  180     0]]

 [[21366  4170]
  [ 9521  6350]]

 [[36129   216]
  [ 4815   247]]

 [[39171   270]
  [ 1445   521]]

 [[28496  2250]
  [ 5507  5154]]

 [[30741  1443]
  [ 6947  2276]]

 [[38668     0]
  [ 2739     0]]

 [[36399   699]
  [ 3167  1142]]

 [[36247   528]
  [ 3587  1045]]

 [[40050     0]
  [ 1357     0]]

 [[37689     0]
  [ 3718     0]]

 [[39562     9]
  [ 1830     6]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

1Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.67      0.32      0.43      2229
            Hernia       0.00      0.00      0.00       180
      Infiltration       0.60      0.40      0.48     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2592 Acc: 0.2039, Time : 93.0067

--------------------------------
|1Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9773    32]
  [  471    76]]

 [[10305     0]
  [   47     0]]

 [[ 4558  1771]
  [ 1750  2273]]

 [[ 9037    46]
  [ 1219    50]]

 [[ 9731    71]
  [  380   170]]

 [[ 7363   333]
  [ 1698   958]]

 [[ 7622   394]
  [ 1781   555]]

 [[ 9706     0]
  [  646     0]]

 [[ 8806   553]
  [  525   468]]

 [[ 9114    88]
  [  955   195]]

 [[10023     0]
  [  329     0]]

 [[ 9403     0]
  [  949     0]]

 [[ 9855    30]
  [  445    22]]

 [[10049     0]
  [  303     0]]]

--------------------------------

1Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.70      0.14      0.23       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.56      0.57      0.56      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2451 Acc: 0.1926, Time : 566.0262

--------------------------------
|2Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38833   345]
  [ 1455   774]]

 [[41227     0]
  [  180     0]]

 [[21399  4137]
  [ 9214  6657]]

 [[36073   272]
  [ 4710   352]]

 [[39157   284]
  [ 1405   561]]

 [[28534  2212]
  [ 5366  5295]]

 [[30697  1487]
  [ 6761  2462]]

 [[38666     2]
  [ 2739     0]]

 [[36372   726]
  [ 3058  1251]]

 [[36199   576]
  [ 3517  1115]]

 [[40050     0]
  [ 1356     1]]

 [[37689     0]
  [ 3718     0]]

 [[39546    25]
  [ 1819    17]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

2Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.69      0.35      0.46      2229
            Hernia       0.00      0.00      0.00       180
      Infiltration       0.62      0.42      0.50     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2573 Acc: 0.1673, Time : 93.0052

--------------------------------
|2Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9675   130]
  [  377   170]]

 [[10305     0]
  [   47     0]]

 [[ 5550   779]
  [ 2747  1276]]

 [[ 8902   181]
  [ 1113   156]]

 [[ 9738    64]
  [  392   158]]

 [[ 7125   571]
  [ 1422  1234]]

 [[ 7601   415]
  [ 1704   632]]

 [[ 9706     0]
  [  646     0]]

 [[ 9075   284]
  [  648   345]]

 [[ 8981   221]
  [  830   320]]

 [[10023     0]
  [  329     0]]

 [[ 9403     0]
  [  949     0]]

 [[ 9854    31]
  [  449    18]]

 [[10049     0]
  [  303     0]]]

--------------------------------

2Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.57      0.31      0.40       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.62      0.32      0.42      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2407 Acc: 0.2068, Time : 565.0764

--------------------------------
|3Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38819   359]
  [ 1408   821]]

 [[41227     0]
  [  180     0]]

 [[21379  4157]
  [ 9126  6745]]

 [[36044   301]
  [ 4653   409]]

 [[39168   273]
  [ 1335   631]]

 [[28555  2191]
  [ 5214  5447]]

 [[30591  1593]
  [ 6520  2703]]

 [[38663     5]
  [ 2738     1]]

 [[36339   759]
  [ 2847  1462]]

 [[36170   605]
  [ 3326  1306]]

 [[40050     0]
  [ 1356     1]]

 [[37689     0]
  [ 3718     0]]

 [[39524    47]
  [ 1783    53]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

3Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.70      0.37      0.48      2229
            Hernia       0.00      0.00      0.00       180
      Infiltration       0.62      0.42      0.50     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2575 Acc: 0.2007, Time : 92.9912

--------------------------------
|3Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9624   181]
  [  321   226]]

 [[10305     0]
  [   47     0]]

 [[ 4986  1343]
  [ 2105  1918]]

 [[ 9004    79]
  [ 1174    95]]

 [[ 9601   201]
  [  290   260]]

 [[ 7336   360]
  [ 1658   998]]

 [[ 7750   266]
  [ 1856   480]]

 [[ 9706     0]
  [  646     0]]

 [[ 8918   441]
  [  575   418]]

 [[ 9113    89]
  [  940   210]]

 [[10023     0]
  [  329     0]]

 [[ 9402     1]
  [  949     0]]

 [[ 9853    32]
  [  448    19]]

 [[10049     0]
  [  303     0]]]

--------------------------------

3Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.56      0.41      0.47       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.59      0.48      0.53      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2359 Acc: 0.2214, Time : 564.3920

--------------------------------
|4Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38810   368]
  [ 1352   877]]

 [[41227     0]
  [  180     0]]

 [[21313  4223]
  [ 8721  7150]]

 [[36002   343]
  [ 4550   512]]

 [[39147   294]
  [ 1264   702]]

 [[28503  2243]
  [ 5014  5647]]

 [[30591  1593]
  [ 6294  2929]]

 [[38659     9]
  [ 2728    11]]

 [[36343   755]
  [ 2728  1581]]

 [[36174   601]
  [ 3184  1448]]

 [[40050     0]
  [ 1353     4]]

 [[37689     0]
  [ 3713     5]]

 [[39514    57]
  [ 1775    61]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

4Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.70      0.39      0.50      2229
            Hernia       0.00      0.00      0.00       180
      Infiltration       0.63      0.45      0.52     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2556 Acc: 0.2042, Time : 92.3147

--------------------------------
|4Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9661   144]
  [  351   196]]

 [[10305     0]
  [   47     0]]

 [[ 4826  1503]
  [ 1969  2054]]

 [[ 8989    94]
  [ 1170    99]]

 [[ 9730    72]
  [  385   165]]

 [[ 7100   596]
  [ 1316  1340]]

 [[ 7814   202]
  [ 1925   411]]

 [[ 9705     1]
  [  644     2]]

 [[ 9045   314]
  [  609   384]]

 [[ 9017   185]
  [  843   307]]

 [[10023     0]
  [  329     0]]

 [[ 9403     0]
  [  949     0]]

 [[ 9835    50]
  [  443    24]]

 [[10049     0]
  [  303     0]]]

--------------------------------

4Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.58      0.36      0.44       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.58      0.51      0.54      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2298 Acc: 0.2363, Time : 563.7517

--------------------------------
|5Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38791   387]
  [ 1233   996]]

 [[41226     1]
  [  180     0]]

 [[21323  4213]
  [ 8364  7507]]

 [[35950   395]
  [ 4414   648]]

 [[39145   296]
  [ 1209   757]]

 [[28641  2105]
  [ 4857  5804]]

 [[30524  1660]
  [ 6053  3170]]

 [[38648    20]
  [ 2717    22]]

 [[36318   780]
  [ 2539  1770]]

 [[36140   635]
  [ 2985  1647]]

 [[40048     2]
  [ 1354     3]]

 [[37685     4]
  [ 3713     5]]

 [[39468   103]
  [ 1735   101]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

5Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.72      0.45      0.55      2229
            Hernia       0.00      0.00      0.00       180
      Infiltration       0.64      0.47      0.54     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2602 Acc: 0.2157, Time : 92.6282

--------------------------------
|5Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9695   110]
  [  397   150]]

 [[10305     0]
  [   47     0]]

 [[ 4438  1891]
  [ 1723  2300]]

 [[ 8916   167]
  [ 1116   153]]

 [[ 9742    60]
  [  413   137]]

 [[ 7331   365]
  [ 1652  1004]]

 [[ 7457   559]
  [ 1579   757]]

 [[ 9699     7]
  [  637     9]]

 [[ 9219   140]
  [  773   220]]

 [[ 8913   289]
  [  782   368]]

 [[10023     0]
  [  329     0]]

 [[ 9402     1]
  [  949     0]]

 [[ 9883     2]
  [  462     5]]

 [[10049     0]
  [  303     0]]]

--------------------------------

5Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.58      0.27      0.37       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.55      0.57      0.56      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2223 Acc: 0.2573, Time : 563.8836

--------------------------------
|6Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38796   382]
  [ 1171  1058]]

 [[41227     0]
  [  175     5]]

 [[21282  4254]
  [ 7993  7878]]

 [[35944   401]
  [ 4281   781]]

 [[39148   293]
  [ 1136   830]]

 [[28573  2173]
  [ 4545  6116]]

 [[30466  1718]
  [ 5671  3552]]

 [[38630    38]
  [ 2694    45]]

 [[36335   763]
  [ 2300  2009]]

 [[36120   655]
  [ 2711  1921]]

 [[40043     7]
  [ 1348     9]]

 [[37679    10]
  [ 3706    12]]

 [[39417   154]
  [ 1672   164]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

6Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.73      0.47      0.58      2229
            Hernia       1.00      0.03      0.05       180
      Infiltration       0.65      0.50      0.56     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2642 Acc: 0.2155, Time : 92.7973

--------------------------------
|6Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9554   251]
  [  314   233]]

 [[10305     0]
  [   47     0]]

 [[ 4439  1890]
  [ 1727  2296]]

 [[ 8979   104]
  [ 1125   144]]

 [[ 9708    94]
  [  373   177]]

 [[ 7068   628]
  [ 1357  1299]]

 [[ 7808   208]
  [ 1909   427]]

 [[ 9675    31]
  [  630    16]]

 [[ 9205   154]
  [  744   249]]

 [[ 8970   232]
  [  834   316]]

 [[10021     2]
  [  328     1]]

 [[ 9403     0]
  [  949     0]]

 [[ 9839    46]
  [  440    27]]

 [[10049     0]
  [  303     0]]]

--------------------------------

6Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.48      0.43      0.45       547
            Hernia       0.00      0.00      0.00        47
      Infiltration       0.55      0.57      0.56      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2130 Acc: 0.2796, Time : 564.3288

--------------------------------
|7Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38813   365]
  [ 1028  1201]]

 [[41219     8]
  [  162    18]]

 [[21281  4255]
  [ 7566  8305]]

 [[35857   488]
  [ 4139   923]]

 [[39151   290]
  [ 1080   886]]

 [[28713  2033]
  [ 4211  6450]]

 [[30496  1688]
  [ 5321  3902]]

 [[38571    97]
  [ 2629   110]]

 [[36316   782]
  [ 2062  2247]]

 [[36119   656]
  [ 2494  2138]]

 [[40026    24]
  [ 1324    33]]

 [[37665    24]
  [ 3685    33]]

 [[39368   203]
  [ 1589   247]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

7Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.77      0.54      0.63      2229
            Hernia       0.69      0.10      0.17       180
      Infiltration       0.66      0.52      0.58     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2713 Acc: 0.2027, Time : 93.0380

--------------------------------
|7Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9548   257]
  [  316   231]]

 [[10305     0]
  [   46     1]]

 [[ 4888  1441]
  [ 2105  1918]]

 [[ 8893   190]
  [ 1067   202]]

 [[ 9630   172]
  [  320   230]]

 [[ 7055   641]
  [ 1330  1326]]

 [[ 7563   453]
  [ 1720   616]]

 [[ 9689    17]
  [  640     6]]

 [[ 9159   200]
  [  710   283]]

 [[ 8665   537]
  [  696   454]]

 [[10022     1]
  [  325     4]]

 [[ 9400     3]
  [  947     2]]

 [[ 9720   165]
  [  388    79]]

 [[10049     0]
  [  303     0]]]

--------------------------------

7Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.47      0.42      0.45       547
            Hernia       1.00      0.02      0.04        47
      Infiltration       0.57      0.48      0.52      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.2019 Acc: 0.3076, Time : 561.8030

--------------------------------
|8Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38813   365]
  [  926  1303]]

 [[41221     6]
  [  154    26]]

 [[21343  4193]
  [ 6958  8913]]

 [[35814   531]
  [ 3988  1074]]

 [[39164   277]
  [  954  1012]]

 [[28767  1979]
  [ 3823  6838]]

 [[30447  1737]
  [ 4858  4365]]

 [[38538   130]
  [ 2547   192]]

 [[36355   743]
  [ 1862  2447]]

 [[36130   645]
  [ 2225  2407]]

 [[40003    47]
  [ 1296    61]]

 [[37636    53]
  [ 3671    47]]

 [[39341   230]
  [ 1490   346]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

8Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.78      0.58      0.67      2229
            Hernia       0.81      0.14      0.25       180
      Infiltration       0.68      0.56      0.62     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2750 Acc: 0.1917, Time : 92.0891

--------------------------------
|8Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9572   233]
  [  334   213]]

 [[10299     6]
  [   42     5]]

 [[ 5318  1011]
  [ 2560  1463]]

 [[ 8960   123]
  [ 1128   141]]

 [[ 9729    73]
  [  395   155]]

 [[ 6681  1015]
  [ 1083  1573]]

 [[ 6941  1075]
  [ 1314  1022]]

 [[ 9617    89]
  [  624    22]]

 [[ 9072   287]
  [  672   321]]

 [[ 8999   203]
  [  882   268]]

 [[ 9996    27]
  [  322     7]]

 [[ 9343    60]
  [  923    26]]

 [[ 9847    38]
  [  437    30]]

 [[10049     0]
  [  303     0]]]

--------------------------------

8Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.48      0.39      0.43       547
            Hernia       0.45      0.11      0.17        47
      Infiltration       0.59      0.36      0.45      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1893 Acc: 0.3401, Time : 561.5744

--------------------------------
|9Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38856   322]
  [  724  1505]]

 [[41222     5]
  [  145    35]]

 [[21531  4005]
  [ 6474  9397]]

 [[35750   595]
  [ 3766  1296]]

 [[39180   261]
  [  902  1064]]

 [[28889  1857]
  [ 3405  7256]]

 [[30523  1661]
  [ 4285  4938]]

 [[38448   220]
  [ 2410   329]]

 [[36366   732]
  [ 1661  2648]]

 [[36150   625]
  [ 1929  2703]]

 [[39968    82]
  [ 1260    97]]

 [[37609    80]
  [ 3591   127]]

 [[39338   233]
  [ 1345   491]]

 [[40279     0]
  [ 1128     0]]]

--------------------------------

9Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.82      0.68      0.74      2229
            Hernia       0.88      0.19      0.32       180
      Infiltration       0.70      0.59      0.64     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.2914 Acc: 0.1971, Time : 93.0410

--------------------------------
|9Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9709    96]
  [  430   117]]

 [[10291    14]
  [   43     4]]

 [[ 4354  1975]
  [ 1765  2258]]

 [[ 8959   124]
  [ 1126   143]]

 [[ 9655   147]
  [  347   203]]

 [[ 6954   742]
  [ 1311  1345]]

 [[ 6957  1059]
  [ 1404   932]]

 [[ 9667    39]
  [  636    10]]

 [[ 8505   854]
  [  484   509]]

 [[ 9077   125]
  [  921   229]]

 [[10019     4]
  [  325     4]]

 [[ 9367    36]
  [  926    23]]

 [[ 9870    15]
  [  448    19]]

 [[10049     0]
  [  303     0]]]

--------------------------------

9Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.55      0.21      0.31       547
            Hernia       0.22      0.09      0.12        47
      Infiltration       0.53      0.56      0.55      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1758 Acc: 0.3731, Time : 563.8250

--------------------------------
|10Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38884   294]
  [  633  1596]]

 [[41208    19]
  [  129    51]]

 [[21783  3753]
  [ 5935  9936]]

 [[35712   633]
  [ 3467  1595]]

 [[39184   257]
  [  817  1149]]

 [[28975  1771]
  [ 3003  7658]]

 [[30547  1637]
  [ 3845  5378]]

 [[38393   275]
  [ 2237   502]]

 [[36424   674]
  [ 1376  2933]]

 [[36161   614]
  [ 1671  2961]]

 [[39948   102]
  [ 1196   161]]

 [[37541   148]
  [ 3501   217]]

 [[39298   273]
  [ 1178   658]]

 [[40278     1]
  [ 1128     0]]]

--------------------------------

10Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.84      0.72      0.77      2229
            Hernia       0.73      0.28      0.41       180
      Infiltration       0.73      0.63      0.67     15871
 

  0%|          | 0/647 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



val Loss: 0.3044 Acc: 0.2046, Time : 92.8279

--------------------------------
|10Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9471   334]
  [  306   241]]

 [[10296     9]
  [   43     4]]

 [[ 3760  2569]
  [ 1485  2538]]

 [[ 8903   180]
  [ 1093   176]]

 [[ 9759    43]
  [  439   111]]

 [[ 6808   888]
  [ 1276  1380]]

 [[ 7042   974]
  [ 1489   847]]

 [[ 9617    89]
  [  617    29]]

 [[ 9004   355]
  [  638   355]]

 [[ 8927   275]
  [  815   335]]

 [[ 9995    28]
  [  314    15]]

 [[ 9353    50]
  [  929    20]]

 [[ 9726   159]
  [  398    69]]

 [[10049     0]
  [  303     0]]]

--------------------------------

10Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.42      0.44      0.43       547
            Hernia       0.31      0.09      0.13        47
      Infiltration       0.50      0.63      0.56      4023
        

  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1612 Acc: 0.4156, Time : 564.3880

--------------------------------
|1Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38912   266]
  [  542  1687]]

 [[41216    11]
  [  109    71]]

 [[21882  3654]
  [ 5354 10517]]

 [[35680   665]
  [ 3191  1871]]

 [[39210   231]
  [  695  1271]]

 [[29206  1540]
  [ 2539  8122]]

 [[30626  1558]
  [ 3283  5940]]

 [[38293   375]
  [ 2100   639]]

 [[36503   595]
  [ 1145  3164]]

 [[36233   542]
  [ 1422  3210]]

 [[39908   142]
  [ 1127   230]]

 [[37466   223]
  [ 3396   322]]

 [[39303   268]
  [ 1024   812]]

 [[40277     2]
  [ 1122     6]]]

--------------------------------

1Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.86      0.76      0.81      2229
            Hernia       0.87      0.39      0.54       180
      Infiltration       0.74      0.66      0.70     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.3261 Acc: 0.2036, Time : 92.6884

--------------------------------
|1Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9664   141]
  [  386   161]]

 [[10297     8]
  [   42     5]]

 [[ 4304  2025]
  [ 1818  2205]]

 [[ 8942   141]
  [ 1142   127]]

 [[ 9711    91]
  [  379   171]]

 [[ 6634  1062]
  [ 1092  1564]]

 [[ 7347   669]
  [ 1656   680]]

 [[ 9506   200]
  [  600    46]]

 [[ 8960   399]
  [  652   341]]

 [[ 8867   335]
  [  831   319]]

 [[10010    13]
  [  324     5]]

 [[ 9179   224]
  [  874    75]]

 [[ 9786    99]
  [  424    43]]

 [[10048     1]
  [  303     0]]]

--------------------------------

1Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.53      0.29      0.38       547
            Hernia       0.38      0.11      0.17        47
      Infiltration       0.52      0.55      0.53      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1466 Acc: 0.4521, Time : 563.9430

--------------------------------
|2Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38938   240]
  [  439  1790]]

 [[41209    18]
  [  107    73]]

 [[22153  3383]
  [ 4875 10996]]

 [[35637   708]
  [ 2829  2233]]

 [[39212   229]
  [  613  1353]]

 [[29357  1389]
  [ 2214  8447]]

 [[30797  1387]
  [ 2822  6401]]

 [[38258   410]
  [ 1871   868]]

 [[36562   536]
  [  935  3374]]

 [[36295   480]
  [ 1212  3420]]

 [[39859   191]
  [ 1058   299]]

 [[37406   283]
  [ 3200   518]]

 [[39249   322]
  [  866   970]]

 [[40270     9]
  [ 1116    12]]]

--------------------------------

2Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.88      0.80      0.84      2229
            Hernia       0.80      0.41      0.54       180
      Infiltration       0.76      0.69      0.73     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.3460 Acc: 0.1669, Time : 92.1716

--------------------------------
|2Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9398   407]
  [  290   257]]

 [[10255    50]
  [   40     7]]

 [[ 5450   879]
  [ 2855  1168]]

 [[ 8531   552]
  [  963   306]]

 [[ 9741    61]
  [  427   123]]

 [[ 6144  1552]
  [  896  1760]]

 [[ 6906  1110]
  [ 1428   908]]

 [[ 9424   282]
  [  587    59]]

 [[ 9011   348]
  [  643   350]]

 [[ 8790   412]
  [  780   370]]

 [[ 9896   127]
  [  297    32]]

 [[ 9298   105]
  [  911    38]]

 [[ 9755   130]
  [  421    46]]

 [[10049     0]
  [  303     0]]]

--------------------------------

2Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.39      0.47      0.42       547
            Hernia       0.12      0.15      0.13        47
      Infiltration       0.57      0.29      0.38      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1333 Acc: 0.4894, Time : 563.1559

--------------------------------
|3Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38954   224]
  [  380  1849]]

 [[41213    14]
  [   90    90]]

 [[22409  3127]
  [ 4310 11561]]

 [[35612   733]
  [ 2576  2486]]

 [[39235   206]
  [  545  1421]]

 [[29521  1225]
  [ 1880  8781]]

 [[30899  1285]
  [ 2409  6814]]

 [[38203   465]
  [ 1655  1084]]

 [[36625   473]
  [  830  3479]]

 [[36291   484]
  [ 1084  3548]]

 [[39846   204]
  [  957   400]]

 [[37325   364]
  [ 3065   653]]

 [[39315   256]
  [  732  1104]]

 [[40262    17]
  [ 1091    37]]]

--------------------------------

3Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.89      0.83      0.86      2229
            Hernia       0.87      0.50      0.63       180
      Infiltration       0.79      0.73      0.76     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.3588 Acc: 0.1684, Time : 92.7797

--------------------------------
|3Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9644   161]
  [  391   156]]

 [[10280    25]
  [   40     7]]

 [[ 4730  1599]
  [ 2211  1812]]

 [[ 8407   676]
  [  928   341]]

 [[ 9625   177]
  [  343   207]]

 [[ 6608  1088]
  [ 1124  1532]]

 [[ 7338   678]
  [ 1734   602]]

 [[ 9391   315]
  [  580    66]]

 [[ 8835   524]
  [  588   405]]

 [[ 8754   448]
  [  761   389]]

 [[ 9937    86]
  [  314    15]]

 [[ 9107   296]
  [  856    93]]

 [[ 9786    99]
  [  417    50]]

 [[10047     2]
  [  303     0]]]

--------------------------------

3Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.49      0.29      0.36       547
            Hernia       0.22      0.15      0.18        47
      Infiltration       0.53      0.45      0.49      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1198 Acc: 0.5326, Time : 561.3431

--------------------------------
|4Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38986   192]
  [  336  1893]]

 [[41213    14]
  [   75   105]]

 [[22756  2780]
  [ 3824 12047]]

 [[35701   644]
  [ 2249  2813]]

 [[39245   196]
  [  485  1481]]

 [[29680  1066]
  [ 1528  9133]]

 [[31035  1149]
  [ 1992  7231]]

 [[38212   456]
  [ 1437  1302]]

 [[36664   434]
  [  704  3605]]

 [[36309   466]
  [  994  3638]]

 [[39845   205]
  [  887   470]]

 [[37239   450]
  [ 2869   849]]

 [[39312   259]
  [  595  1241]]

 [[40245    34]
  [ 1075    53]]]

--------------------------------

4Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.91      0.85      0.88      2229
            Hernia       0.88      0.58      0.70       180
      Infiltration       0.81      0.76      0.78     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.3975 Acc: 0.1749, Time : 93.4505

--------------------------------
|4Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9599   206]
  [  363   184]]

 [[10273    32]
  [   38     9]]

 [[ 4811  1518]
  [ 2281  1742]]

 [[ 8484   599]
  [  954   315]]

 [[ 9516   286]
  [  297   253]]

 [[ 6997   699]
  [ 1485  1171]]

 [[ 7064   952]
  [ 1491   845]]

 [[ 9312   394]
  [  549    97]]

 [[ 8786   573]
  [  575   418]]

 [[ 8630   572]
  [  724   426]]

 [[ 9937    86]
  [  306    23]]

 [[ 9236   167]
  [  904    45]]

 [[ 9829    56]
  [  437    30]]

 [[10047     2]
  [  303     0]]]

--------------------------------

4Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.47      0.34      0.39       547
            Hernia       0.22      0.19      0.20        47
      Infiltration       0.53      0.43      0.48      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.1091 Acc: 0.5650, Time : 563.3080

--------------------------------
|5Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[38994   184]
  [  295  1934]]

 [[41212    15]
  [   71   109]]

 [[22942  2594]
  [ 3375 12496]]

 [[35659   686]
  [ 1958  3104]]

 [[39265   176]
  [  426  1540]]

 [[29776   970]
  [ 1380  9281]]

 [[31169  1015]
  [ 1732  7491]]

 [[38203   465]
  [ 1242  1497]]

 [[36709   389]
  [  616  3693]]

 [[36365   410]
  [  879  3753]]

 [[39814   236]
  [  825   532]]

 [[37211   478]
  [ 2583  1135]]

 [[39328   243]
  [  510  1326]]

 [[40221    58]
  [ 1046    82]]]

--------------------------------

5Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.91      0.87      0.89      2229
            Hernia       0.88      0.61      0.72       180
      Infiltration       0.83      0.79      0.81     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.4194 Acc: 0.1665, Time : 92.8681

--------------------------------
|5Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9556   249]
  [  347   200]]

 [[10289    16]
  [   38     9]]

 [[ 4301  2028]
  [ 1958  2065]]

 [[ 8601   482]
  [  986   283]]

 [[ 9667   135]
  [  363   187]]

 [[ 7083   613]
  [ 1583  1073]]

 [[ 7035   981]
  [ 1488   848]]

 [[ 9215   491]
  [  548    98]]

 [[ 8987   372]
  [  646   347]]

 [[ 8208   994]
  [  645   505]]

 [[10004    19]
  [  325     4]]

 [[ 8726   677]
  [  792   157]]

 [[ 9752   133]
  [  411    56]]

 [[ 9990    59]
  [  296     7]]]

--------------------------------

5Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.45      0.37      0.40       547
            Hernia       0.36      0.19      0.25        47
      Infiltration       0.50      0.51      0.51      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.0993 Acc: 0.5937, Time : 561.0056

--------------------------------
|6Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[39002   176]
  [  283  1946]]

 [[41209    18]
  [   68   112]]

 [[23197  2339]
  [ 2959 12912]]

 [[35717   628]
  [ 1748  3314]]

 [[39264   177]
  [  379  1587]]

 [[29838   908]
  [ 1259  9402]]

 [[31221   963]
  [ 1595  7628]]

 [[38229   439]
  [ 1135  1604]]

 [[36727   371]
  [  552  3757]]

 [[36369   406]
  [  768  3864]]

 [[39839   211]
  [  732   625]]

 [[37128   561]
  [ 2277  1441]]

 [[39326   245]
  [  466  1370]]

 [[40191    88]
  [  991   137]]]

--------------------------------

6Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.92      0.87      0.89      2229
            Hernia       0.86      0.62      0.72       180
      Infiltration       0.85      0.81      0.83     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.4494 Acc: 0.1621, Time : 92.7006

--------------------------------
|6Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9473   332]
  [  332   215]]

 [[10300     5]
  [   43     4]]

 [[ 4300  2029]
  [ 2011  2012]]

 [[ 7996  1087]
  [  824   445]]

 [[ 9642   160]
  [  347   203]]

 [[ 7019   677]
  [ 1500  1156]]

 [[ 7158   858]
  [ 1590   746]]

 [[ 9614    92]
  [  623    23]]

 [[ 8980   379]
  [  663   330]]

 [[ 8824   378]
  [  796   354]]

 [[ 9980    43]
  [  321     8]]

 [[ 9018   385]
  [  844   105]]

 [[ 9245   640]
  [  323   144]]

 [[ 9962    87]
  [  301     2]]]

--------------------------------

6Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.39      0.39      0.39       547
            Hernia       0.44      0.09      0.14        47
      Infiltration       0.50      0.50      0.50      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.0902 Acc: 0.6277, Time : 560.9463

--------------------------------
|7Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[39024   154]
  [  238  1991]]

 [[41213    14]
  [   56   124]]

 [[23504  2032]
  [ 2634 13237]]

 [[35758   587]
  [ 1501  3561]]

 [[39289   152]
  [  328  1638]]

 [[29897   849]
  [ 1104  9557]]

 [[31303   881]
  [ 1388  7835]]

 [[38263   405]
  [  982  1757]]

 [[36750   348]
  [  573  3736]]

 [[36403   372]
  [  699  3933]]

 [[39837   213]
  [  663   694]]

 [[37105   584]
  [ 2044  1674]]

 [[39331   240]
  [  432  1404]]

 [[40167   112]
  [  948   180]]]

--------------------------------

7Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.93      0.89      0.91      2229
            Hernia       0.90      0.69      0.78       180
      Infiltration       0.87      0.83      0.85     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.4709 Acc: 0.1594, Time : 92.3146

--------------------------------
|7Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9504   301]
  [  341   206]]

 [[10287    18]
  [   42     5]]

 [[ 5033  1296]
  [ 2438  1585]]

 [[ 8904   179]
  [ 1135   134]]

 [[ 9508   294]
  [  298   252]]

 [[ 6512  1184]
  [ 1086  1570]]

 [[ 6621  1395]
  [ 1370   966]]

 [[ 9425   281]
  [  595    51]]

 [[ 8277  1082]
  [  449   544]]

 [[ 8799   403]
  [  772   378]]

 [[ 9993    30]
  [  319    10]]

 [[ 9014   389]
  [  842   107]]

 [[ 9825    60]
  [  443    24]]

 [[10043     6]
  [  301     2]]]

--------------------------------

7Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.41      0.38      0.39       547
            Hernia       0.22      0.11      0.14        47
      Infiltration       0.55      0.39      0.46      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.0815 Acc: 0.6553, Time : 563.2546

--------------------------------
|8Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[39032   146]
  [  232  1997]]

 [[41218     9]
  [   48   132]]

 [[23688  1848]
  [ 2268 13603]]

 [[35774   571]
  [ 1392  3670]]

 [[39308   133]
  [  277  1689]]

 [[29982   764]
  [ 1011  9650]]

 [[31388   796]
  [ 1238  7985]]

 [[38260   408]
  [  838  1901]]

 [[36784   314]
  [  457  3852]]

 [[36460   315]
  [  636  3996]]

 [[39843   207]
  [  574   783]]

 [[37116   573]
  [ 1762  1956]]

 [[39347   224]
  [  401  1435]]

 [[40152   127]
  [  878   250]]]

--------------------------------

8Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.93      0.90      0.91      2229
            Hernia       0.94      0.73      0.82       180
      Infiltration       0.88      0.86      0.87     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.4923 Acc: 0.1804, Time : 92.6706

--------------------------------
|8Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9541   264]
  [  336   211]]

 [[10297     8]
  [   42     5]]

 [[ 3592  2737]
  [ 1498  2525]]

 [[ 8840   243]
  [ 1096   173]]

 [[ 9614   188]
  [  328   222]]

 [[ 7046   650]
  [ 1474  1182]]

 [[ 6737  1279]
  [ 1338   998]]

 [[ 9377   329]
  [  575    71]]

 [[ 8888   471]
  [  616   377]]

 [[ 8926   276]
  [  849   301]]

 [[ 9944    79]
  [  308    21]]

 [[ 9022   381]
  [  840   109]]

 [[ 9714   171]
  [  402    65]]

 [[10017    32]
  [  300     3]]]

--------------------------------

8Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.44      0.39      0.41       547
            Hernia       0.38      0.11      0.17        47
      Infiltration       0.48      0.63      0.54      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.0749 Acc: 0.6782, Time : 560.9044

--------------------------------
|9Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[39042   136]
  [  224  2005]]

 [[41209    18]
  [   58   122]]

 [[23846  1690]
  [ 2016 13855]]

 [[35796   549]
  [ 1222  3840]]

 [[39300   141]
  [  269  1697]]

 [[30055   691]
  [  948  9713]]

 [[31447   737]
  [ 1105  8118]]

 [[38291   377]
  [  756  1983]]

 [[36810   288]
  [  437  3872]]

 [[36460   315]
  [  622  4010]]

 [[39857   193]
  [  517   840]]

 [[37091   598]
  [ 1525  2193]]

 [[39373   198]
  [  348  1488]]

 [[40130   149]
  [  798   330]]]

--------------------------------

9Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.94      0.90      0.92      2229
            Hernia       0.87      0.68      0.76       180
      Infiltration       0.89      0.87      0.88     15871
   

  0%|          | 0/647 [00:00<?, ?it/s]


val Loss: 0.5240 Acc: 0.1802, Time : 92.6649

--------------------------------
|9Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9703   102]
  [  410   137]]

 [[10298     7]
  [   44     3]]

 [[ 3220  3109]
  [ 1286  2737]]

 [[ 8679   404]
  [ 1041   228]]

 [[ 9676   126]
  [  362   188]]

 [[ 6962   734]
  [ 1444  1212]]

 [[ 7022   994]
  [ 1548   788]]

 [[ 9449   257]
  [  588    58]]

 [[ 8797   562]
  [  574   419]]

 [[ 8945   257]
  [  844   306]]

 [[ 9838   185]
  [  295    34]]

 [[ 9019   384]
  [  854    95]]

 [[ 9521   364]
  [  352   115]]

 [[ 9992    57]
  [  298     5]]]

--------------------------------

9Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.57      0.25      0.35       547
            Hernia       0.30      0.06      0.11        47
      Infiltration       0.47      0.68      0.55      4023
          

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



train Loss: 0.0683 Acc: 0.7033, Time : 562.1646

--------------------------------
|10Epoch trainphase multilabel_confusion_matrix report|
--------------------------------

[[[39031   147]
  [  217  2012]]

 [[41211    16]
  [   54   126]]

 [[24033  1503]
  [ 1815 14056]]

 [[35804   541]
  [ 1108  3954]]

 [[39316   125]
  [  246  1720]]

 [[30152   594]
  [  806  9855]]

 [[31502   682]
  [ 1008  8215]]

 [[38322   346]
  [  668  2071]]

 [[36814   284]
  [  423  3886]]

 [[36482   293]
  [  543  4089]]

 [[39875   175]
  [  457   900]]

 [[37142   547]
  [ 1336  2382]]

 [[39382   189]
  [  318  1518]]

 [[40119   160]
  [  694   434]]]

--------------------------------

10Epoch trainphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.93      0.90      0.92      2229
            Hernia       0.89      0.70      0.78       180
      Infiltration       0.90      0.89      0.89     15871
 

  0%|          | 0/647 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



val Loss: 0.5447 Acc: 0.1698, Time : 93.5563

--------------------------------
|10Epoch valphase multilabel_confusion_matrix report|
--------------------------------

[[[ 9589   216]
  [  370   177]]

 [[10274    31]
  [   39     8]]

 [[ 3344  2985]
  [ 1358  2665]]

 [[ 8340   743]
  [  931   338]]

 [[ 9670   132]
  [  351   199]]

 [[ 7039   657]
  [ 1500  1156]]

 [[ 7446   570]
  [ 1777   559]]

 [[ 9092   614]
  [  539   107]]

 [[ 8805   554]
  [  588   405]]

 [[ 8940   262]
  [  884   266]]

 [[ 9828   195]
  [  295    34]]

 [[ 9215   188]
  [  905    44]]

 [[ 9749   136]
  [  410    57]]

 [[10007    42]
  [  300     3]]]

--------------------------------

10Epoch valphase classification report
--------------------------------
                    precision    recall  f1-score   support

      Cardiomegaly       0.45      0.32      0.38       547
            Hernia       0.21      0.17      0.19        47
      Infiltration       0.47      0.66      0.55      4023
        

  0%|          | 0/2588 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: An exception was ignored while fetching the attribute `__array_interface__` from an object of type 'PngImageFile'.  With the exception of `AttributeError` NumPy will always raise this exception in the future.  Raise this deprecation warning to see the original exception. (Warning added NumPy 1.21)
  # Remove the CWD from sys.path while we load stuff.


TypeError: ignored